name: Build Frontend Assets

on:
  push:
    branches: [ main ]
    paths:
      - 'js/src/**'
      - 'package.json'
      - 'webpack.config.js'
      - 'tsconfig.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build frontend assets
      run: npm run build
    
    - name: Check for changes
      id: check_changes
      run: |
        if [ -n "$(git status --porcelain js/dist/)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push if changed
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add js/dist/
        git commit -m "build: Compile frontend assets [skip ci]"
        git push